[package]
name = "marc21"
version = "0.1.0"
edition = "2021"
authors = ["Nico Wagner <nwagner@protonmail.com>"]
license = "MIT OR Unlicense"

[dependencies]
bstr = "1.0.1"
nom = "7.1.1"
thiserror = "1.0.37"

[dev-dependencies]
anyhow = "1.0.66"
nom-test-helpers = "6.1.3"
